src/Entity/Player.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlayerRepository")
 */
class Player
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="players")
     */
    private $team_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTeamId(): ?Team
    {
        return $this->team_id;
    }

    public function setTeamId(?Team $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }
}

src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 */
class Team
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Player", mappedBy="team_id")
     */
    private $players;

    public function __construct()
    {
        $this->players = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Player[]
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
            $player->setTeamId($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->players->contains($player)) {
            $this->players->removeElement($player);
            // set the owning side to null (unless already changed)
            if ($player->getTeamId() === $this) {
                $player->setTeamId(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController {

    public function home() {
        $name = 'Lucas';
        return $this->render('index.html.twig', [
            'name' => $name
        ]);
    }

    public function homeName($name) {
        return $this->render('index_name.html.twig', [
            'name' => $name
        ]);
    }

}

src/Controller/PlayersController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PlayersController extends AbstractController {
    public function getPlayers() {

        $repo =  $this->getDoctrine()->getRepository('App:Player');
        $players = $repo->findAll();

        return $this->render('players.html.twig', [
            'players' => $players
        ]);
    }

    public function addTeam() {

        $em = $this->getDoctrine()->getManager();
        $newTeam = new Team();
        $newTeam->setName('COB-YNOV Rubgy');

        $em->persist($newTeam);
        $em->flush();

        return $this->render('teams.html.twig', [
            'team_created' => $newTeam
        ]);
    }

    public function addPlayerTotTeam(){
        $em = $this->getDoctrine()->getManager();
        $repoPlayer =  $this->getDoctrine()->getRepository('App:Player');
        $repoTeam =  $this->getDoctrine()->getRepository('App:Team');

        $player = $repoPlayer->find(1);
        $team = $repoTeam->find(1);

        $player->setTeamId($team);

        $em->persist($player);
        $em->flush();

        return new \Symfony\Component\HttpFoundation\Response('OK');
    }

    public function addPlayerTotTeamTwo($idPlayer, $idTeam){
        $em = $this->getDoctrine()->getManager();
        $repoPlayer =  $this->getDoctrine()->getRepository('App:Player');
        $repoTeam =  $this->getDoctrine()->getRepository('App:Team');

        $player = $repoPlayer->find($idPlayer);
        $team = $repoTeam->find($idTeam);

        $player->setTeamId($team);

        $em->persist($player);
        $em->flush();

        return new \Symfony\Component\HttpFoundation\Response('OK');
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}     
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-white" href="#">LaboSymfo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active text-white">
                        <a class="nav-link text-white" href="{{ path('home')}}">Accueil<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ path('players')}}">Players</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">A propos</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% block body %}
            Block Parent
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}
    Home
{% endblock %}

{% block body%}
    <div class="container">
        <br>
        Salut {{ name }}
    </div>
{% endblock %}

templates/index_name.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Home | {{ name }}
{% endblock %}

{% block body %}
    <div class="container">
        <br>
        <!-- {{ parent() }} -->
        Re coucou {{ name }}
    </div>
{% endblock %}

templates/players.html.twig
{% extends 'base.html.twig' %}

{% block title %} Player {% endblock %}

{% block body %}
    <div class="container">
        <br>
        <h2>Player</h2><br>
        <ul>
        {% for player in players %}
                <li>Id Joueur : {{ player.id }}</li>
                <li>Equipe : {{ player.teamId.name }}</li>
                <li>Prénom : {{ player.firstname }}</li>
                <li>Nom : {{ player.lastname }}</li>
                <li>Age : {{ player.age }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/teams.html.twig
{% extends 'base.html.twig' %}

{% block title %} Player {% endblock %}

{% block body %}
    {{ team_created.name }}
{% endblock %}